# Generated by Django 3.1.2 on 2020-10-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id_cliente')),
                ('nom_cliente', models.CharField(max_length=30, verbose_name='nombre_cliente')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=30, verbose_name='id_producto')),
                ('nom_producto', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.CharField(max_length=50, verbose_name='id_factura')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_detalle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.producto')),
            ],
            options={
                'verbose_name': 'DetalleFactura',
            },
        ),
    ]
