# Generated by Django 3.1.2 on 2020-10-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nom_cliente',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nom_producto',
            field=models.TextField(verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
