# Generated by Django 3.1.2 on 2020-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20201022_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id',
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_factura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
